### ISSUE TITLE
Default class is set to 'is-active' (Bulma) not 'active' Bootstrap

### ISSUE THREAD

**Issue by coryrose1** [DevMarketer/LaravelEasyNav#3]
Hey,

Just wanted to give a heads up that on a fresh install today (10/16/2017), the default configuration for the active class was set to 'is-active'.

No problem with this really, but the current documentation reflects that the class is 'active' / Bootstrap by default.

Thanks and love your videos!

**Comment by jacurtis** [comment]
Thanks for mentioning this. I have fixed it now. The default will now be `"active"` instead of `"is-active"` to reflect the documentation and the most common framework by far, which is Bootstrap.

**Comment by jacurtis** [comment]
Pushed to live. This is active now in version `1.0.4`
