### ISSUE TITLE
urlContains() undefined

### ISSUE THREAD

**Issue by ghost** [DevMarketer/LaravelEasyNav#8]
Hi Alex! There is an error in your package when try to use urlContains:
`Call to undefined method DevMarketer\EasyNav\EasyNav::urlContains() `
All another working fine

**Comment by belaarany** [comment]
Checking the source code, you are correct, there is no such method called `urlContains()`.

However I found a similar method which should be the one you are looking for. It's called `urlDoesContain()`. Can you please try using this instead? If this is the one you are looking for then the documentation should be corrected.

Hope it makes sense. :smiley:

**Comment by ghost** [comment]
You are correct! =) Method urlDoesContains() is what I expected for =) Thx so much!
